"""create tables

Revision ID: 000c3587f640
Revises: 
Create Date: 2020-08-07 02:05:30.689856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000c3587f640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electric_hookup', sa.Boolean(), nullable=True),
    sa.Column('water_hookup', sa.Boolean(), nullable=True),
    sa.Column('septic_hookup', sa.Boolean(), nullable=True),
    sa.Column('assigned_parking', sa.Boolean(), nullable=True),
    sa.Column('tow_vehicle_parking', sa.Boolean(), nullable=True),
    sa.Column('trash_removal', sa.Boolean(), nullable=True),
    sa.Column('water_front', sa.Boolean(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('internet_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('necessities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rv_compatible', sa.Boolean(), nullable=True),
    sa.Column('generators_allowed', sa.Boolean(), nullable=True),
    sa.Column('fires_allowed', sa.Boolean(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('pad_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('domicile_type', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('user_info', sa.String(length=2000), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('gps_coords', sa.String(length=100), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('host_notes', sa.String(length=2000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('necessity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['necessity_id'], ['necessities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_address', sa.String(length=100), nullable=False),
    sa.Column('starting_city', sa.String(length=50), nullable=False),
    sa.Column('starting_state', sa.String(length=20), nullable=False),
    sa.Column('ending_address', sa.String(length=100), nullable=False),
    sa.Column('ending_city', sa.String(length=50), nullable=False),
    sa.Column('ending_state', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('noise', sa.Integer(), nullable=True),
    sa.Column('safety', sa.Integer(), nullable=True),
    sa.Column('cleanliness', sa.Integer(), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.Column('site_quality', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=2000), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('calendar')
    op.drop_table('trips')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('necessities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
